default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'metiner'
  password: 'q1w2e3RR'
development:
  <<: *default
  database: ilacTakas_dev
test:
  <<: *default
  database: ilacTakas_test
production:
  <<: *default
  database: <%= ENV['POSTGRESQL_ADDON_DB'] %>
  host: <%= ENV['POSTGRESQL_ADDON_HOST'] %>
  password: <%= ENV['POSTGRESQL_ADDON_PASSWORD'] %>
  port: <%= ENV['POSTGRESQL_ADDON_PORT'] %>
  username: <%= ENV['POSTGRESQL_ADDON_USER'] %>
